// src/components/sections/ContactSection.vue
<script setup>
import { ref, inject, computed } from 'vue'
import { translations, personalData } from '../../i18n/translations.js'

const currentLang = inject('currentLang')
const t = computed(() => translations[currentLang.value])

// Form state
const form = ref({
  name: '',
  email: '',
  message: '',
})

const handleSubmit = () => {
  console.log('Form submitted:', form.value)
  // Adicione sua lógica de envio aqui
  alert('Mensagem enviada! (simulação)')
  form.value = { name: '', email: '', message: '' }
}
</script>

<template>
  <section id="contact" class="py-20 lg:py-32 pb-32 md:pb-20">
    <div class="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
      
      <!-- Header -->
      <div class="text-center mb-12">
        <h2 class="text-3xl md:text-4xl font-bold mb-4">{{ t.contact.title }}</h2>
        <p class="text-[var(--text-secondary)] max-w-xl mx-auto">{{ t.contact.subtitle }}</p>
      </div>
      
      <!-- Form (centered on desktop) -->
      <div class="max-w-xl mx-auto">
        <form @submit.prevent="handleSubmit" class="glass-card p-6 md:p-8 space-y-6">
          
          <!-- Name -->
          <div>
            <label class="flex items-center gap-2 text-sm font-medium mb-2">
              <svg class="w-4 h-4 text-[var(--accent)]" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M16 7a4 4 0 11-8 0 4 4 0 018 0zM12 14a7 7 0 00-7 7h14a7 7 0 00-7-7z" />
              </svg>
              {{ t.contact.nameLabel }}
            </label>
            <input
              v-model="form.name"
              type="text"
              :placeholder="t.contact.namePlaceholder"
              required
              class="w-full px-4 py-3 rounded-lg bg-[var(--input)] border border-[var(--border-color)] focus:border-[var(--accent)] focus:outline-none transition-colors"
            />
          </div>
          
          <!-- Email -->
          <div>
            <label class="flex items-center gap-2 text-sm font-medium mb-2">
              <svg class="w-4 h-4 text-[var(--accent)]" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M16 12a4 4 0 10-8 0 4 4 0 008 0zm0 0v1.5a2.5 2.5 0 005 0V12a9 9 0 10-9 9m4.5-1.206a8.959 8.959 0 01-4.5 1.207" />
              </svg>
              {{ t.contact.emailLabel }}
            </label>
            <input
              v-model="form.email"
              type="email"
              :placeholder="t.contact.emailPlaceholder"
              required
              class="w-full px-4 py-3 rounded-lg bg-[var(--input)] border border-[var(--border-color)] focus:border-[var(--accent)] focus:outline-none transition-colors"
            />
          </div>
          
          <!-- Message -->
          <div>
            <label class="flex items-center gap-2 text-sm font-medium mb-2">
              <svg class="w-4 h-4 text-[var(--accent)]" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M8 10h.01M12 10h.01M16 10h.01M9 16H5a2 2 0 01-2-2V6a2 2 0 012-2h14a2 2 0 012 2v8a2 2 0 01-2 2h-5l-5 5v-5z" />
              </svg>
              {{ t.contact.messageLabel }}
            </label>
            <textarea
              v-model="form.message"
              :placeholder="t.contact.messagePlaceholder"
              rows="4"
              required
              class="w-full px-4 py-3 rounded-lg bg-[var(--input)] border border-[var(--border-color)] focus:border-[var(--accent)] focus:outline-none transition-colors resize-none"
            />
          </div>
          
          <!-- Submit -->
          <button type="submit" class="btn-primary w-full flex items-center justify-center gap-2">
            {{ t.contact.send }}
            <svg class="w-5 h-5" fill="none" stroke="currentColor" viewBox="0 0 24 24">
              <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M12 19l9 2-9-18-9 18 9-2zm0 0v-8" />
            </svg>
          </button>
        </form>
        
        <!-- Social Links -->
        <div class="mt-12 text-center">
          <p class="text-xs text-[var(--text-muted)] tracking-widest mb-4">{{ t.contact.connectWith }}</p>
          <div class="flex justify-center gap-4">
            <a 
              :href="personalData.social.github"
              target="_blank"
              rel="noopener noreferrer"
              class="w-12 h-12 rounded-full glass-card flex items-center justify-center hover:border-[var(--accent)] transition-colors"
            >
              <svg class="w-5 h-5" fill="currentColor" viewBox="0 0 24 24">
                <path d="M12 0c-6.626 0-12 5.373-12 12 0 5.302 3.438 9.8 8.207 11.387.599.111.793-.261.793-.577v-2.234c-3.338.726-4.033-1.416-4.033-1.416-.546-1.387-1.333-1.756-1.333-1.756-1.089-.745.083-.729.083-.729 1.205.084 1.839 1.237 1.839 1.237 1.07 1.834 2.807 1.304 3.492.997.107-.775.418-1.305.762-1.604-2.665-.305-5.467-1.334-5.467-5.931 0-1.311.469-2.381 1.236-3.221-.124-.303-.535-1.524.117-3.176 0 0 1.008-.322 3.301 1.23.957-.266 1.983-.399 3.003-.404 1.02.005 2.047.138 3.006.404 2.291-1.552 3.297-1.23 3.297-1.23.653 1.653.242 2.874.118 3.176.77.84 1.235 1.911 1.235 3.221 0 4.609-2.807 5.624-5.479 5.921.43.372.823 1.102.823 2.222v3.293c0 .319.192.694.801.576 4.765-1.589 8.199-6.086 8.199-11.386 0-6.627-5.373-12-12-12z"/>
              </svg>
            </a>
            <a 
              :href="personalData.social.linkedin"
              target="_blank"
              rel="noopener noreferrer"
              class="w-12 h-12 rounded-full glass-card flex items-center justify-center hover:border-[var(--accent)] transition-colors"
            >
              <svg class="w-5 h-5" fill="currentColor" viewBox="0 0 24 24">
                <path d="M20.447 20.452h-3.554v-5.569c0-1.328-.027-3.037-1.852-3.037-1.853 0-2.136 1.445-2.136 2.939v5.667H9.351V9h3.414v1.561h.046c.477-.9 1.637-1.85 3.37-1.85 3.601 0 4.267 2.37 4.267 5.455v6.286zM5.337 7.433c-1.144 0-2.063-.926-2.063-2.065 0-1.138.92-2.063 2.063-2.063 1.14 0 2.064.925 2.064 2.063 0 1.139-.925 2.065-2.064 2.065zm1.782 13.019H3.555V9h3.564v11.452zM22.225 0H1.771C.792 0 0 .774 0 1.729v20.542C0 23.227.792 24 1.771 24h20.451C23.2 24 24 23.227 24 22.271V1.729C24 .774 23.2 0 22.222 0h.003z"/>
              </svg>
            </a>
            <a 
              :href="`mailto:${personalData.social.email}`"
              class="w-12 h-12 rounded-full glass-card flex items-center justify-center hover:border-[var(--accent)] transition-colors"
            >
              <svg class="w-5 h-5" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M3 8l7.89 5.26a2 2 0 002.22 0L21 8M5 19h14a2 2 0 002-2V7a2 2 0 00-2-2H5a2 2 0 00-2 2v10a2 2 0 002 2z" />
              </svg>
            </a>
          </div>
        </div>
      </div>
      
      <!-- Footer -->
      <footer class="mt-16 text-center text-sm text-[var(--text-muted)]">
        {{ t.contact.footer }}
      </footer>
    </div>
  </section>
</template>

// components/sections/contact-section.tsx
"use client";

import { useLanguage } from "@/contexts/language-context";
import { User, Mail, MessageSquare, Send, Github, Briefcase, MailIcon } from "lucide-react";

export function ContactSection() {
  const { t } = useLanguage();

  const socialLinks = [
    { icon: Github, href: "#", label: "GitHub" },
    { icon: Briefcase, href: "#", label: "Portfolio" },
    { icon: MailIcon, href: "#", label: "Email" },
  ];

  return (
    <section className="min-h-screen py-24 flex items-center">
      <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 w-full">
        {/* Header - Centered on desktop */}
        <div className="text-center mb-12">
          <h2 className="text-4xl sm:text-5xl font-bold text-foreground mb-4">
            {t("contact.title")}
          </h2>
          <p className="text-lg text-muted-foreground max-w-2xl mx-auto">
            {t("contact.subtitle")}
          </p>
        </div>

        {/* Form - Centered and constrained width on desktop */}
        <div className="max-w-2xl mx-auto">
          <div className="p-8 rounded-2xl bg-[var(--glass-bg)] border border-[var(--glass-border)] backdrop-blur-md">
            <form className="space-y-6">
              {/* Name Field */}
              <div>
                <label className="flex items-center gap-2 text-sm font-medium text-foreground mb-2">
                  <User className="w-4 h-4 text-primary" />
                  {t("contact.name")}
                </label>
                <input
                  type="text"
                  placeholder={t("contact.namePlaceholder")}
                  className="w-full px-4 py-3 rounded-xl bg-[var(--input)] border border-[var(--glass-border)] text-foreground placeholder:text-muted-foreground focus:outline-none focus:ring-2 focus:ring-primary/50 focus:border-primary transition-all"
                />
              </div>

              {/* Email Field */}
              <div>
                <label className="flex items-center gap-2 text-sm font-medium text-foreground mb-2">
                  <Mail className="w-4 h-4 text-primary" />
                  {t("contact.email")}
                </label>
                <input
                  type="email"
                  placeholder={t("contact.emailPlaceholder")}
                  className="w-full px-4 py-3 rounded-xl bg-[var(--input)] border border-[var(--glass-border)] text-foreground placeholder:text-muted-foreground focus:outline-none focus:ring-2 focus:ring-primary/50 focus:border-primary transition-all"
                />
              </div>

              {/* Message Field */}
              <div>
                <label className="flex items-center gap-2 text-sm font-medium text-foreground mb-2">
                  <MessageSquare className="w-4 h-4 text-primary" />
                  {t("contact.message")}
                </label>
                <textarea
                  rows={5}
                  placeholder={t("contact.messagePlaceholder")}
                  className="w-full px-4 py-3 rounded-xl bg-[var(--input)] border border-[var(--glass-border)] text-foreground placeholder:text-muted-foreground focus:outline-none focus:ring-2 focus:ring-primary/50 focus:border-primary transition-all resize-none"
                />
              </div>

              {/* Submit Button */}
              <button
                type="submit"
                className="w-full flex items-center justify-center gap-2 px-8 py-4 bg-primary text-primary-foreground rounded-xl font-medium hover:bg-primary/90 transition-all duration-200 shadow-lg shadow-primary/25"
              >
                {t("contact.send")}
                <Send className="w-5 h-5" />
              </button>
            </form>
          </div>

          {/* Social Links */}
          <div className="mt-12 text-center">
            <span className="text-xs font-semibold tracking-wider text-muted-foreground mb-6 block">
              {t("contact.connect")}
            </span>
            <div className="flex justify-center gap-4">
              {socialLinks.map((link) => (
                <a
                  key={link.label}
                  href={link.href}
                  className="w-14 h-14 rounded-2xl bg-[var(--glass-bg)] border border-[var(--glass-border)] flex items-center justify-center text-muted-foreground hover:text-foreground hover:border-primary/50 transition-all duration-200 backdrop-blur-sm"
                  aria-label={link.label}
                >
                  <link.icon className="w-6 h-6" />
                </a>
              ))}
            </div>
          </div>

          {/* Footer */}
          <div className="mt-16 text-center">
            <p className="text-sm text-muted-foreground">
              © 2024 {t("footer.copyright")} • {t("footer.tagline")}
            </p>
          </div>
        </div>
      </div>
    </section>
  );
}
