// src/components/sections/HeroSection.vue
<script setup>
import { inject, computed } from 'vue'
import { translations, personalData } from '../../i18n/translations.js'

const currentLang = inject('currentLang')
const t = computed(() => translations[currentLang.value])
</script>

<template>
  <section id="home" class="min-h-screen flex items-center pt-16">
    <div class="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 py-12 lg:py-0 w-full">
      
      <!-- Desktop: Split Layout -->
      <div class="flex flex-col lg:flex-row items-center gap-12 lg:gap-20">
        
        <!-- Texto (Left) -->
        <div class="flex-1 text-center lg:text-left">
          
          <!-- Badge -->
          <span class="inline-block px-4 py-2 rounded-full text-sm font-medium text-[var(--accent)] border border-[var(--accent)] mb-6 animate-fade-in-up">
            {{ t.hero.badge }}
          </span>
          
          <!-- Nome -->
          <h1 class="text-4xl md:text-5xl lg:text-6xl font-bold mb-6 animate-fade-in-up delay-100">
            {{ t.hero.name }}
          </h1>
          
          <!-- Bio -->
          <p class="text-lg text-[var(--text-secondary)] max-w-xl mx-auto lg:mx-0 mb-8 animate-fade-in-up delay-200">
            {{ t.hero.bio }}
          </p>
          
          <!-- Botões CTA -->
          <div class="flex flex-col sm:flex-row gap-4 justify-center lg:justify-start mb-10 animate-fade-in-up delay-300">
            <a href="#projects" class="btn-primary flex items-center justify-center gap-2">
              <svg class="w-5 h-5" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M13 10V3L4 14h7v7l9-11h-7z" />
              </svg>
              {{ t.hero.viewProjects }}
            </a>
            <a href="#" class="btn-outline flex items-center justify-center gap-2">
              <svg class="w-5 h-5" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M9 12h6m-6 4h6m2 5H7a2 2 0 01-2-2V5a2 2 0 012-2h5.586a1 1 0 01.707.293l5.414 5.414a1 1 0 01.293.707V19a2 2 0 01-2 2z" />
              </svg>
              {{ t.hero.resume }}
            </a>
          </div>
          
          <!-- Expertise Tags -->
          <div class="animate-fade-in-up delay-400">
            <p class="text-xs text-[var(--text-muted)] tracking-widest mb-3">{{ t.hero.expertise }}</p>
            <div class="flex flex-wrap gap-2 justify-center lg:justify-start">
              <span 
                v-for="skill in personalData.expertise" 
                :key="skill"
                class="tag"
              >
                <span class="text-[var(--accent)]">#</span>
                {{ skill }}
              </span>
            </div>
          </div>
        </div>
        
        <!-- Foto (Right) -->
        <div class="flex-shrink-0">
          <div class="relative">
            <!-- Glow Effect -->
            <div class="absolute inset-0 rounded-full bg-[var(--accent)] opacity-20 blur-3xl scale-110" />
            
            <!-- Ring -->
            <div class="relative w-64 h-64 lg:w-80 lg:h-80 rounded-full border-4 border-[var(--accent)]/30 p-2">
              <img
                :src="personalData.profileImage"
                :alt="personalData.name"
                class="w-full h-full rounded-full object-cover"
              />
            </div>
          </div>
        </div>
        
      </div>
    </div>
  </section>
</template>

// components/sections/hero-section.tsx
"use client";

import { useLanguage } from "@/contexts/language-context";
import { Rocket, FileText } from "lucide-react";
import Image from "next/image";

interface HeroSectionProps {
  onNavigate: (section: string) => void;
}

export function HeroSection({ onNavigate }: HeroSectionProps) {
  const { t } = useLanguage();

  const expertise = ["Terraform", "AWS", "React", "Node.js", "Docker", "TypeScript"];

  return (
    <section className="min-h-screen flex items-center pt-16">
      <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 w-full">
        <div className="grid lg:grid-cols-2 gap-12 lg:gap-16 items-center">
          {/* Left side - Text content */}
          <div className="order-2 lg:order-1 text-center lg:text-left">
            <span className="inline-block px-4 py-2 rounded-full bg-primary/10 text-primary text-sm font-medium tracking-wider mb-6">
              {t("hero.role")}
            </span>
            
            <h1 className="text-4xl sm:text-5xl lg:text-6xl font-bold text-foreground mb-6 text-balance">
              {t("hero.name")}
            </h1>
            
            <p className="text-lg sm:text-xl text-muted-foreground max-w-xl mx-auto lg:mx-0 mb-8 leading-relaxed text-pretty">
              {t("hero.bio")}
            </p>

            {/* CTA Buttons */}
            <div className="flex flex-col sm:flex-row gap-4 justify-center lg:justify-start mb-12">
              <button
                onClick={() => onNavigate("projects")}
                className="flex items-center justify-center gap-2 px-8 py-4 bg-primary text-primary-foreground rounded-xl font-medium hover:bg-primary/90 transition-all duration-200 shadow-lg shadow-primary/25"
              >
                <Rocket className="w-5 h-5" />
                {t("hero.viewProjects")}
              </button>
              <button
                className="flex items-center justify-center gap-2 px-8 py-4 bg-[var(--glass-bg)] border border-[var(--glass-border)] text-foreground rounded-xl font-medium hover:bg-muted/50 transition-all duration-200 backdrop-blur-sm"
              >
                <FileText className="w-5 h-5" />
                {t("hero.resume")}
              </button>
            </div>

            {/* Expertise Tags */}
            <div>
              <span className="text-xs font-semibold tracking-wider text-muted-foreground mb-4 block">
                {t("hero.expertise")}
              </span>
              <div className="flex flex-wrap gap-3 justify-center lg:justify-start">
                {expertise.map((skill) => (
                  <span
                    key={skill}
                    className="px-4 py-2 rounded-lg bg-[var(--glass-bg)] border border-[var(--glass-border)] text-foreground text-sm font-medium backdrop-blur-sm"
                  >
                    <span className="text-primary mr-1">#</span>
                    {skill}
                  </span>
                ))}
              </div>
            </div>
          </div>

          {/* Right side - Profile Image */}
          <div className="order-1 lg:order-2 flex justify-center lg:justify-end">
            <div className="relative">
              {/* Glow effect */}
              <div className="absolute inset-0 bg-primary/30 rounded-full blur-3xl scale-110" />
              
              {/* Image container */}
              <div className="relative w-64 h-64 sm:w-80 sm:h-80 lg:w-96 lg:h-96 rounded-full overflow-hidden border-4 border-primary/30 shadow-2xl">
                <Image
                  src="/images/profile.jpg"
                  alt="Profile photo"
                  fill
                  className="object-cover object-center"
                  priority
                />
              </div>
              
              {/* Decorative ring */}
              <div className="absolute inset-0 rounded-full border-2 border-primary/20 scale-125 animate-pulse" />
            </div>
          </div>
        </div>
      </div>
    </section>
  );
}
