// components/sections/experience-section.tsx
"use client";

import { useLanguage } from "@/contexts/language-context";
import { Briefcase, GraduationCap, Code2, Award } from "lucide-react";
import Image from "next/image";

interface ExperienceSectionProps {
  onNavigate: (section: string) => void;
}

export function ExperienceSection({ onNavigate }: ExperienceSectionProps) {
  const { t } = useLanguage();

  const skills = [
    { name: "React.js", icon: "JS" },
    { name: "Node.js", icon: "JS" },
    { name: "AWS / GCP", icon: "cloud" },
    { name: "Docker", icon: "docker" },
    { name: "MongoDB", icon: "db" },
    { name: "CyberSec", icon: "shield" },
  ];

  return (
    <section className="min-h-screen py-24">
      <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
        {/* Header */}
        <div className="mb-16">
          <h2 className="text-4xl sm:text-5xl font-bold text-foreground mb-4">
            {t("exp.title")}
          </h2>
          <p className="text-lg text-muted-foreground max-w-2xl">
            {t("exp.subtitle")}
          </p>
        </div>

        {/* Main content grid - Side by side on desktop */}
        <div className="grid lg:grid-cols-2 gap-8">
          {/* Left column - Experience & Education */}
          <div className="space-y-8">
            {/* Experience Section */}
            <div>
              <div className="flex items-center gap-3 mb-6">
                <Briefcase className="w-6 h-6 text-primary" />
                <h3 className="text-xl font-semibold text-foreground">
                  {t("exp.experience")}
                </h3>
              </div>

              {/* Timeline */}
              <div className="relative space-y-6">
                {/* Timeline line */}
                <div className="absolute left-4 top-0 bottom-0 w-0.5 bg-gradient-to-b from-primary via-primary/50 to-transparent" />

                {/* Job 1 */}
                <div className="relative pl-12">
                  <div className="absolute left-0 top-1 w-8 h-8 rounded-full bg-primary flex items-center justify-center">
                    <Code2 className="w-4 h-4 text-primary-foreground" />
                  </div>
                  <div className="p-6 rounded-2xl bg-[var(--glass-bg)] border border-[var(--glass-border)] backdrop-blur-md">
                    <div className="flex flex-wrap items-center gap-3 mb-2">
                      <h4 className="text-lg font-semibold text-foreground">
                        {t("job1.title")}
                      </h4>
                      <span className="px-2 py-1 text-xs font-medium bg-primary/20 text-primary rounded-full">
                        {t("exp.present")}
                      </span>
                    </div>
                    <p className="text-primary font-medium mb-1">@ {t("job1.company")}</p>
                    <p className="text-sm text-muted-foreground mb-4">{t("job1.period")}</p>
                    <ul className="space-y-2 text-muted-foreground">
                      <li className="flex items-start gap-2">
                        <span className="text-primary mt-1">•</span>
                        {t("job1.desc1")}
                      </li>
                      <li className="flex items-start gap-2">
                        <span className="text-primary mt-1">•</span>
                        {t("job1.desc2")}
                      </li>
                    </ul>
                  </div>
                </div>

                {/* Job 2 */}
                <div className="relative pl-12">
                  <div className="absolute left-0 top-1 w-8 h-8 rounded-full bg-muted flex items-center justify-center">
                    <Briefcase className="w-4 h-4 text-muted-foreground" />
                  </div>
                  <div className="p-6 rounded-2xl bg-[var(--glass-bg)] border border-[var(--glass-border)] backdrop-blur-md">
                    <h4 className="text-lg font-semibold text-foreground mb-2">
                      {t("job2.title")}
                    </h4>
                    <p className="text-primary font-medium mb-1">@ {t("job2.company")}</p>
                    <p className="text-sm text-muted-foreground mb-4">{t("job2.period")}</p>
                    <ul className="space-y-2 text-muted-foreground">
                      <li className="flex items-start gap-2">
                        <span className="text-primary mt-1">•</span>
                        {t("job2.desc1")}
                      </li>
                      <li className="flex items-start gap-2">
                        <span className="text-primary mt-1">•</span>
                        {t("job2.desc2")}
                      </li>
                    </ul>
                  </div>
                </div>
              </div>
            </div>

            {/* Education Section */}
            <div>
              <div className="flex items-center gap-3 mb-6">
                <GraduationCap className="w-6 h-6 text-primary" />
                <h3 className="text-xl font-semibold text-foreground">
                  {t("exp.education")}
                </h3>
              </div>

              <div className="space-y-4">
                {/* Education 1 */}
                <div className="p-6 rounded-2xl bg-[var(--glass-bg)] border border-[var(--glass-border)] backdrop-blur-md flex gap-4">
                  <div className="flex-1">
                    <h4 className="text-lg font-semibold text-foreground mb-1">
                      {t("edu1.title")}
                    </h4>
                    <p className="text-muted-foreground mb-2">{t("edu1.school")}</p>
                    <p className="text-sm text-primary">{t("edu1.period")}</p>
                  </div>
                  <div className="w-20 h-20 rounded-lg overflow-hidden relative hidden sm:block">
                    <Image
                      src="/images/university.jpg"
                      alt="University"
                      fill
                      className="object-cover"
                    />
                  </div>
                </div>

                {/* Education 2 */}
                <div className="p-6 rounded-2xl bg-[var(--glass-bg)] border border-[var(--glass-border)] backdrop-blur-md flex items-center gap-4">
                  <div className="flex-1">
                    <h4 className="text-lg font-semibold text-foreground mb-1">
                      {t("edu2.title")}
                    </h4>
                    <p className="text-muted-foreground">{t("edu2.school")}</p>
                  </div>
                  <div className="w-12 h-12 rounded-full bg-primary/20 flex items-center justify-center">
                    <Award className="w-6 h-6 text-primary" />
                  </div>
                </div>
              </div>
            </div>
          </div>

          {/* Right column - Skills Grid */}
          <div>
            <div className="flex items-center gap-3 mb-6">
              <Code2 className="w-6 h-6 text-primary" />
              <h3 className="text-xl font-semibold text-foreground">
                {t("exp.skills")}
              </h3>
            </div>

            <div className="grid grid-cols-2 gap-4">
              {skills.map((skill) => (
                <div
                  key={skill.name}
                  className="p-6 rounded-2xl bg-[var(--glass-bg)] border border-[var(--glass-border)] backdrop-blur-md hover:border-primary/50 transition-all duration-300 group"
                >
                  <div className="flex items-center gap-4">
                    <div className="w-12 h-12 rounded-xl bg-primary/10 flex items-center justify-center group-hover:bg-primary/20 transition-colors">
                      <span className="text-primary font-bold text-sm">{skill.icon}</span>
                    </div>
                    <span className="font-medium text-foreground">{skill.name}</span>
                  </div>
                </div>
              ))}
            </div>

            {/* CTA Button */}
            <button
              onClick={() => onNavigate("projects")}
              className="mt-8 w-full flex items-center justify-center gap-2 px-8 py-4 bg-primary text-primary-foreground rounded-xl font-medium hover:bg-primary/90 transition-all duration-200 shadow-lg shadow-primary/25"
            >
              {t("exp.viewProjects")}
              <span>→</span>
            </button>
          </div>
        </div>
      </div>
    </section>
  );
}

// src/components/sections/ExperienceSection.vue
<script setup>
import { inject, computed } from 'vue'
import { translations, experienceData, educationData, skillsData } from '../../i18n/translations.js'

const currentLang = inject('currentLang')
const t = computed(() => translations[currentLang.value])

// Helper para pegar texto traduzido
const getText = (obj) => obj[currentLang.value] || obj.pt || obj
</script>

<template>
  <section id="experience" class="py-20 lg:py-32">
    <div class="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
      
      <!-- Header -->
      <div class="mb-16">
        <h2 class="text-3xl md:text-4xl font-bold mb-4">{{ t.experience.title }}</h2>
        <p class="text-[var(--text-secondary)]">{{ t.experience.subtitle }}</p>
      </div>
      
      <!-- Desktop: Side by Side Layout -->
      <div class="grid lg:grid-cols-2 gap-8 lg:gap-12">
        
        <!-- Left: Timeline -->
        <div>
          <h3 class="flex items-center gap-2 text-xl font-semibold mb-6">
            <svg class="w-5 h-5 text-[var(--accent)]" fill="none" stroke="currentColor" viewBox="0 0 24 24">
              <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M21 13.255A23.931 23.931 0 0112 15c-3.183 0-6.22-.62-9-1.745M16 6V4a2 2 0 00-2-2h-4a2 2 0 00-2 2v2m4 6h.01M5 20h14a2 2 0 002-2V8a2 2 0 00-2-2H5a2 2 0 00-2 2v10a2 2 0 002 2z" />
            </svg>
            {{ t.experience.experienceTitle }}
          </h3>
          
          <!-- Timeline -->
          <div class="relative">
            <!-- Line -->
            <div class="absolute left-5 top-0 bottom-0 w-0.5 bg-[var(--border-color)]" />
            
            <!-- Items -->
            <div 
              v-for="(exp, index) in experienceData" 
              :key="index"
              class="relative pl-14 pb-8 last:pb-0"
            >
              <!-- Dot -->
              <div class="absolute left-3 w-5 h-5 rounded-full bg-[var(--accent)] flex items-center justify-center">
                <svg class="w-3 h-3 text-white" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                  <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M10 20l4-16m4 4l4 4-4 4M6 16l-4-4 4-4" />
                </svg>
              </div>
              
              <!-- Card -->
              <div class="glass-card p-5 glow-hover">
                <div class="flex items-start justify-between mb-2">
                  <h4 class="font-semibold">{{ getText(exp.title) }}</h4>
                  <span 
                    v-if="exp.isCurrent" 
                    class="text-xs px-2 py-1 rounded bg-[var(--accent)]/20 text-[var(--accent)]"
                  >
                    {{ t.experience.present }}
                  </span>
                </div>
                <p class="text-[var(--accent)] text-sm mb-1">@ {{ exp.company }}</p>
                <p class="text-[var(--text-muted)] text-sm mb-3">{{ getText(exp.period) }}</p>
                <ul class="space-y-1">
                  <li 
                    v-for="(item, i) in getText(exp.description)" 
                    :key="i"
                    class="text-sm text-[var(--text-secondary)] flex items-start gap-2"
                  >
                    <span class="text-[var(--accent)] mt-1">•</span>
                    {{ item }}
                  </li>
                </ul>
              </div>
            </div>
          </div>
        </div>
        
        <!-- Right: Education + Skills -->
        <div class="space-y-8">
          
          <!-- Education -->
          <div>
            <h3 class="flex items-center gap-2 text-xl font-semibold mb-6">
              <svg class="w-5 h-5 text-[var(--accent)]" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                <path d="M12 14l9-5-9-5-9 5 9 5z" />
                <path d="M12 14l6.16-3.422a12.083 12.083 0 01.665 6.479A11.952 11.952 0 0012 20.055a11.952 11.952 0 00-6.824-2.998 12.078 12.078 0 01.665-6.479L12 14z" />
              </svg>
              {{ t.experience.educationTitle }}
            </h3>
            
            <div class="space-y-4">
              <div 
                v-for="(edu, index) in educationData" 
                :key="index"
                class="glass-card p-4 glow-hover flex items-center gap-4"
              >
                <div v-if="edu.image" class="w-16 h-16 rounded-lg overflow-hidden flex-shrink-0">
                  <img :src="edu.image" :alt="edu.institution" class="w-full h-full object-cover" />
                </div>
                <div v-else class="w-16 h-16 rounded-lg bg-[var(--accent)]/20 flex items-center justify-center flex-shrink-0">
                  <svg class="w-8 h-8 text-[var(--accent)]" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                    <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M9 12l2 2 4-4M7.835 4.697a3.42 3.42 0 001.946-.806 3.42 3.42 0 014.438 0 3.42 3.42 0 001.946.806 3.42 3.42 0 013.138 3.138 3.42 3.42 0 00.806 1.946 3.42 3.42 0 010 4.438 3.42 3.42 0 00-.806 1.946 3.42 3.42 0 01-3.138 3.138 3.42 3.42 0 00-1.946.806 3.42 3.42 0 01-4.438 0 3.42 3.42 0 00-1.946-.806 3.42 3.42 0 01-3.138-3.138 3.42 3.42 0 00-.806-1.946 3.42 3.42 0 010-4.438 3.42 3.42 0 00.806-1.946 3.42 3.42 0 013.138-3.138z" />
                  </svg>
                </div>
                <div>
                  <h4 class="font-semibold">{{ getText(edu.title) }}</h4>
                  <p class="text-sm text-[var(--text-secondary)]">{{ edu.institution }}</p>
                  <p class="text-sm text-[var(--accent)]">{{ edu.period }}</p>
                </div>
              </div>
            </div>
          </div>
          
          <!-- Skills Grid -->
          <div>
            <h3 class="flex items-center gap-2 text-xl font-semibold mb-6">
              <svg class="w-5 h-5 text-[var(--accent)]" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M17.657 18.657A8 8 0 016.343 7.343S7 9 9 10c0-2 .5-5 2.986-7C14 5 16.09 5.777 17.656 7.343A7.975 7.975 0 0120 13a7.975 7.975 0 01-2.343 5.657z" />
              </svg>
              {{ t.experience.skillsTitle }}
            </h3>
            
            <div class="grid grid-cols-2 gap-3">
              <div 
                v-for="skill in skillsData" 
                :key="skill.name"
                class="glass-card p-4 glow-hover flex items-center gap-3"
              >
                <div class="w-8 h-8 rounded bg-[var(--accent)]/20 flex items-center justify-center">
                  <svg class="w-4 h-4 text-[var(--accent)]" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                    <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M10 20l4-16m4 4l4 4-4 4M6 16l-4-4 4-4" />
                  </svg>
                </div>
                <span class="font-medium text-sm">{{ skill.name }}</span>
              </div>
            </div>
          </div>
          
          <!-- CTA Button -->
          <a href="#projects" class="btn-primary w-full flex items-center justify-center gap-2">
            {{ t.experience.viewProjects }}
            <svg class="w-5 h-5" fill="none" stroke="currentColor" viewBox="0 0 24 24">
              <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M17 8l4 4m0 0l-4 4m4-4H3" />
            </svg>
          </a>
        </div>
      </div>
    </div>
  </section>
</template>
